package com.lancastersolutions.serviceflow;

import android.Manifest;import android.annotation.SuppressLint;import android.app.Activity;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.webkit.*;import android.widget.Toast;
import androidx.annotation.NonNull;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import androidx.core.content.FileProvider;import androidx.webkit.WebViewAssetLoader;
import java.io.*;import java.text.SimpleDateFormat;import java.util.*;

public class MainActivity extends Activity {
 static final int FILE=4101, GEO=4102, CAMERA=4103; WebView web; ValueCallback<Uri[]> callback; Uri cameraUri; GeolocationPermissions.Callback geoCallback; String geoOrigin;
 @SuppressLint({"SetJavaScriptEnabled","JavascriptInterface"}) public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setGeolocationEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);web.addJavascriptInterface(new Bridge(),"ServiceFlowAndroid");WebViewAssetLoader loader=new WebViewAssetLoader.Builder().addPathHandler("/assets/",new WebViewAssetLoader.AssetsPathHandler(this)).build();web.setWebViewClient(new WebViewClient(){public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return loader.shouldInterceptRequest(r.getUrl());}});web.setWebChromeClient(new WebChromeClient(){public void onGeolocationPermissionsShowPrompt(String o,GeolocationPermissions.Callback c){if(hasGeo())c.invoke(o,true,false);else{geoOrigin=o;geoCallback=c;ActivityCompat.requestPermissions(MainActivity.this,new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},GEO);}}public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> c,FileChooserParams p){if(callback!=null)callback.onReceiveValue(null);callback=c;choose(p);return true;}});if(b==null)web.loadUrl("https://appassets.androidplatform.net/assets/www/index.html");else web.restoreState(b);}
 boolean hasGeo(){return ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED||ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED;} boolean hasCamera(){return ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED;}
 void choose(WebChromeClient.FileChooserParams p){if(!hasCamera())ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.CAMERA},CAMERA);Intent pick;try{pick=p.createIntent();}catch(Exception e){pick=new Intent(Intent.ACTION_GET_CONTENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);}ArrayList<Intent> extra=new ArrayList<>();if(hasCamera()){Intent cam=camera();if(cam!=null)extra.add(cam);}Intent chooser=Intent.createChooser(pick,"Capture or select job evidence");chooser.putExtra(Intent.EXTRA_INITIAL_INTENTS,extra.toArray(new Intent[0]));startActivityForResult(chooser,FILE);}
 Intent camera(){Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);if(i.resolveActivity(getPackageManager())==null)return null;try{File dir=getExternalFilesDir(Environment.DIRECTORY_PICTURES);if(dir==null)dir=getCacheDir();File f=File.createTempFile("JOB_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+"_",".jpg",dir);cameraUri=FileProvider.getUriForFile(this,BuildConfig.APPLICATION_ID+".fileprovider",f);i.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);return i;}catch(IOException e){return null;}}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r!=FILE||callback==null)return;Uri[] out=null;if(result==RESULT_OK){if(data!=null&&data.getData()!=null)out=new Uri[]{data.getData()};else if(cameraUri!=null)out=new Uri[]{cameraUri};}callback.onReceiveValue(out);callback=null;cameraUri=null;}
 public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==GEO&&geoCallback!=null){geoCallback.invoke(geoOrigin,hasGeo(),false);geoCallback=null;}if(r==CAMERA&&!hasCamera())Toast.makeText(this,"Camera permission denied; existing photos can still be selected.",Toast.LENGTH_LONG).show();}
 public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();} protected void onSaveInstanceState(@NonNull Bundle b){web.saveState(b);super.onSaveInstanceState(b);} final class Bridge{@JavascriptInterface public String getDefaultApiUrl(){return BuildConfig.DEFAULT_API_URL;}@JavascriptInterface public String getVersionName(){return BuildConfig.VERSION_NAME;}}
}
